version: '2.1'

volumes:
  db-backups:
  db-data:

services:
  db:
    image: kartoza/postgis:13.0
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=gravelly
      - POSTGRES_USER=gravelly
      - POSTGRES_PASS=test123
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    restart: on-failure
    healthcheck:
      test: "exit 0"
    ports:
      - 5432:5432

